// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
//holki
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAebxtgOBjancX9O5i_e_wnDhfz4elH5I8',
    appId: '1:144232808813:android:4d0fa9d5ce163b0fc39a64',
    messagingSenderId: '144232808813',
    projectId: 'ahhhhhhh-c76c1',
    databaseURL: 'https://ahhhhhhh-c76c1-default-rtdb.firebaseio.com',
    storageBucket: 'ahhhhhhh-c76c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvFkLv_zZQB_1iAm6YXo_f4GA5-KuTD7k',
    appId: '1:144232808813:ios:987bc36f4f79c1bbc39a64',
    messagingSenderId: '144232808813',
    projectId: 'ahhhhhhh-c76c1',
    databaseURL: 'https://ahhhhhhh-c76c1-default-rtdb.firebaseio.com',
    storageBucket: 'ahhhhhhh-c76c1.appspot.com',
    iosBundleId: 'com.example.gymh', 
  );
}
